<?php

$faq = [
  ["What time do you work?", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet."],
  ["May I contact you directly?", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet."],
  ["How long will it take me to improve?", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet."],
  ["What are your fees?", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet."],
  ["Is it online or in-person?", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet."],
  ["Do you take insurance?", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe officia veritatis animi labore quibusdam. Cupiditate porro minima id culpa vel dignissimos, ex sequi commodi illum? Lorem ipsum dolor sit amet."],
];